export XDG_CURRENT_DESKTOP=sway

# fix issues with java application
# https://github.com/swaywm/sway/wiki#issues-with-java-applications
export _JAVA_AWT_WM_NONREPARENTING=1

# tell qt to use the native wayland backend
# https://github.com/swaywm/sway/wiki#disabling-client-side-qt-decorations
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION="1"
