# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
[env]
# TERM variable
#
# This value is used to set the `$TERM` environment variable for
# each instance of Alacritty. If it is not present, alacritty will
# check the local terminfo database and use `alacritty` if it is
# available, otherwise `xterm-256color` is used.
TERM = "alacritty"

[window]
# Window decorations
#
# Values for `decorations`:
#     - full: Borders and title bar
#     - none: Neither borders nor title bar
#
# Values for `decorations` (macOS only):
#     - transparent: Title bar, transparent background and title bar buttons
#     - buttonless: Title bar, transparent background, but no title bar buttons
decorations = "none"

[scrolling]
# Maximum number of lines in the scrollback buffer.
# Specifying '0' will disable scrolling.
# I use tmux for scrolling instead.
history = 0

[font]
size = 13.0

[font.normal]
family = "Iosevka Term Nerd Font"
#family = "Hack Nerd Font"
style = "Regular"

[cursor]
# Cursor style
#
# Values for `style`:
#   - ▇ Block
#   - _ Underline
#   - | Beam
style = "Block"
# Thickness of the cursor relative to the cell width as floating point number
# from `0.0` to `1.0`.
thickness = 0.15

[general]
import = [
    # Import the Solarized Dark theme.
    "~/.config/alacritty/solarized_dark.toml"
]
# Live config reload (changes require restart).
live_config_reload = true
