" some additional relevant links with good explanations
" should put these in a blog post or something...
" colortest.vim                     :help colorest
" hitest.vim                        :help hitest
" colors available in (g)vim        http://vim.wikia.com/wiki/View_all_colors_available_to_gvim
" cool vim things                   http://www.oualline.com/vim/10/top_10.html

" if certain utility code is needed, then use the util.vim file
source ~/.vimrc.d/util.vim
" if certain configs need to be applied first, then apply them in the init.vim file
source ~/.vimrc.d/init.vim

for file in split( system('ls ~/.vimrc.d/*.vim', ' ') )
    if file !~ '.*util.*' && file !~ '.*init.*' && file !~ '.*final.*'
        "echo file
        exec 'source ' . file
    endif
endfor

" if certain configs need to be applied last, then apply them in the final.vim file
source ~/.vimrc.d/final.vim

" optional machine specific configs to be kept out of version control
" sourcing this last means that default settings can be overwritten
if FileIsPresent('~/.vimrc.add')
    exec 'source ~/.vimrc.add'
endif
