#! env python

import subprocess
import json
from time import sleep

def exec_cmd(cmd):
    p = subprocess.Popen(cmd, stdout = subprocess.PIPE)
    sleep(0.2)
    return p.communicate()[0]

# get the current user
user = exec_cmd( ['whoami'] )
user = user[:-1]    # remove trailing '\n'

# read names of hosts from file
hfile = '/home/%s/.ssh/tmux-ssh-hosts' % (user,)  # file with my ssh hosts
with open(hfile, 'r') as fhandle:
    hosts = json.loads( fhandle.read() )

tmux_cmd = ['tmux', '-S', '/tmp/tmux-ssh']

for idx, (group, targets) in enumerate(hosts.items()):
    if idx == 0:
        # rename existing session to ssh
        exec_cmd( tmux_cmd + ['rename-session', group] )
    else:
        # for future reference:
        # -d    the new session is attached to the current terminal
        #       unless -d is given; without -d, you get the "unset $TMUX" message
        # -s    sets the name of the new group
        exec_cmd( tmux_cmd + ['new-session', '-d', '-s', group] )

    # now change to the newly created session
    exec_cmd( tmux_cmd + ['switch-client', '-t', group] )

    for idx2, target in enumerate(targets):
        # tmux_idx = idx2 + 1 because tmux starts numbering of windows from 1, not 0
        # set by line "set-option -g base-index 1" in the tmux config file
        tmux_idx = idx2 + 1
        if idx2 == 0:
            # first window already exists so we rename it
            exec_cmd( tmux_cmd + ['rename-window', '-t', '%s:%i' % (group, tmux_idx), target])
        else:
            # future windows need to be created
            exec_cmd( tmux_cmd + ['new-window', '-t', '%s:%i' % (group, tmux_idx), '-n', target] )
        exec_cmd( tmux_cmd + ['select-window', '-t', '%s:%s' % (group, target)] )
        exec_cmd( tmux_cmd + ['send-keys', '-t', '%s:%s' % (group, target), 'alias con="ssh %s"' % (target,), 'Enter'] )
