#! env python

import subprocess
from time import sleep

def exec_cmd(cmd):
    p = subprocess.Popen(cmd, stdout = subprocess.PIPE)
    return p.communicate()[0]

# get the current user
user = exec_cmd( ['whoami'] )
user = user[:-1]    # remove trailing '\n'

# variables
sname = 'ssh'                               # session name
hfile = '/home/%s/.ssh/my_hosts' % (user,)  # file with my ssh hosts

# rename existing session to ssh
exec_cmd( ['tmux', 'rename-session', sname] )
exec_cmd( ['tmux', 'rename-window', 'zero'] )

# read names of hosts from file
fhandle = open(hfile, 'r')
code = fhandle.read()
exec(code)                  # sets the 'hosts' variable

# create new windows for each ssh connection
for host in hosts:
    exec_cmd( ['tmux', 'new-window', '-t', sname, '-n', host] ); sleep(0.15)
    exec_cmd( ['tmux', 'select-window', '-t', host] )
    exec_cmd( ['tmux', 'send-keys', '-t', host, 'alias con="ssh %s"' % (host,), 'Enter'] ); sleep(0.15)
